"""Freeze the RAG memory snapshot used by A0-A8 evaluation (Part: RAG
PRECONDITION).

Mirrors the exact hash-and-verify pattern `eval_sets.py` already uses for
the frozen evaluation set: a manifest carries a content hash; `verify()`
re-hashes the LIVE file and reports drift rather than assuming it away.

Freezing does NOT copy `rag_memory_v2.jsonl` to a separate file -- a
detached copy could silently fall out of sync with the file `retrieve()`
actually reads. The manifest records what the file contained AT FREEZE
TIME; `verify()` is how a caller (in particular `preflight.py`) detects
that it has since changed (e.g. a run in "adaptive" learning_mode appended
to it after the freeze was declared).
"""
from __future__ import annotations

import hashlib
import json
import time
from pathlib import Path
from typing import Any

_ROOT = Path(__file__).resolve().parents[2]
# Pre-campaign audit fix (2026-08-09): this module carried its OWN
# hardcoded rag_memory_v2.jsonl path, separate from run_raptor_v2.py's
# RAG_MEMORY_V2 -- which Stage 1.6 versioned to rag_memory_v2_post_cload_
# v1.jsonl. Left unfixed, build_clean_snapshot() called with no explicit
# source_path would have silently read the OLD file (which the campaign
# never writes to), producing a "clean" snapshot with zero new records --
# not a leakage risk, but a silent no-op that would have looked like a
# successful rebuild. Must track the SAME path run_raptor_v2.py writes to.
RAG_MEMORY_V2 = (_ROOT / "artifacts/publication_v2/selfimprove"
                 / "rag_memory_v2_post_cload_v1.jsonl")


def _content_hash(lines: list[str]) -> str:
    # hashes the RAW lines, not re-parsed/re-serialised JSON -- any
    # byte-level change (reorder, edit, append, delete) must be detected,
    # not just a change to the parsed record set
    return hashlib.sha256(
        "\n".join(lines).encode("utf-8")).hexdigest()[:16]


def _read_lines(path: Path) -> list[str]:
    if not path.is_file():
        return []
    return [x for x in path.read_text(encoding="utf-8").splitlines() if x.strip()]


def manifest_path(source_path: Path | None = None) -> Path:
    source_path = source_path or RAG_MEMORY_V2
    return source_path.with_suffix(".freeze.json")


def freeze_rag_snapshot(source_path: Path | None = None) -> dict[str, Any]:
    """Write the freeze manifest for the CURRENT contents of
    `rag_memory_v2.jsonl`. Overwrites any prior manifest -- re-freezing is
    an explicit, deliberate act (e.g. after growing the RAG pool and
    deciding it is now ready), not something that happens by accident."""
    source_path = source_path or RAG_MEMORY_V2
    lines = _read_lines(source_path)
    records = [json.loads(x) for x in lines]
    usable = sum(1 for r in records if r.get("stability"))
    manifest = {
        "source_path": str(source_path),
        "record_count": len(records),
        "usable_record_count": usable,
        "content_hash": _content_hash(lines),
        "frozen_at": time.strftime("%Y-%m-%d %H:%M:%S"),
    }
    manifest_path(source_path).write_text(
        json.dumps(manifest, indent=1), encoding="utf-8")
    return manifest


def verify(source_path: Path | None = None) -> dict[str, Any]:
    """frozen=False if no manifest exists yet. drifted=True if the live
    file's content hash no longer matches the manifest -- e.g. an adaptive
    run appended to rag_memory_v2.jsonl after the freeze was declared."""
    source_path = source_path or RAG_MEMORY_V2
    mp = manifest_path(source_path)
    if not mp.is_file():
        return {"frozen": False, "drifted": False,
                "detail": f"no freeze manifest at {mp}"}
    manifest = json.loads(mp.read_text(encoding="utf-8"))
    live_hash = _content_hash(_read_lines(source_path))
    drifted = live_hash != manifest.get("content_hash")
    return {"frozen": True, "drifted": drifted,
            "detail": ("matches frozen manifest" if not drifted else
                       f"DRIFTED: manifest={manifest.get('content_hash')} "
                       f"live={live_hash} -- re-freeze deliberately or "
                       "investigate the unexpected write"),
            "manifest": manifest}


def build_clean_snapshot(min_timestamp: float, *,
                         source_path: Path | None = None,
                         out_path: Path | None = None) -> dict[str, Any]:
    """Write a FILTERED COPY of rag_memory_v2.jsonl containing only records
    whose call_id timestamp is >= min_timestamp -- excludes anything not
    provably generated by the currently-fixed pipeline. Safe to run
    alongside a live calibration batch still appending to the source file
    (read-only on the source; writes a separate file). Re-runnable/
    idempotent -- call again after the source has grown to pick up more
    clean records; the output is fully overwritten each time, never
    appended to, so it can never accumulate duplicates or drift from
    "exactly what currently qualifies."

    The returned path is meant to be passed as run_pipeline's `rag_memory`
    kwarg (or run_ablation_v3.py's --rag-memory), NOT to replace
    rag_memory_v2.jsonl itself.
    """
    import re
    source_path = source_path or RAG_MEMORY_V2
    out_path = out_path or source_path.with_name(
        source_path.stem + "_clean.jsonl")
    kept = []
    for x in _read_lines(source_path):
        r = json.loads(x)
        m = re.search(r"(\d{13})", str(r.get("call_id", "")))
        ts = int(m.group(1)) / 1000 if m else None
        if ts is not None and ts >= min_timestamp:
            kept.append(x)
    out_path.write_text("\n".join(kept) + ("\n" if kept else ""),
                        encoding="utf-8")
    usable = sum(1 for x in kept if json.loads(x).get("stability"))
    return {"out_path": str(out_path), "kept": len(kept),
            "usable": usable, "min_timestamp": min_timestamp,
            "source_total": len(_read_lines(source_path))}
