"""Case C, Step 7: retrain the topology proposer on the repaired corpus.

Problem A was never a decoding problem. Every one of the 85 training prompts
carried exactly ONE target, generated by the deterministic rule
`stages = 1 if gain<30 else 2 if gain<70 else 3`. The model reproduced that
distribution perfectly (100% spec-match) and therefore could not propose
alternatives: 20 attempts at T=1.5 yielded at most 2 distinct graphs.
Diversity absent from the data cannot be recovered by temperature.

corpus_diverse.json fixes the data: 5 verified-realizable targets per spec,
765 records, max family share 22%, five distinct canonical graphs.

This writes a NEW adapter and does not touch artifacts/stage3e4/sft_adapter,
so the baseline every diversity number is measured against stays intact and
the comparison remains possible.

GPU, roughly 2-3 h at the default step count.

Run from Agentic_Raptor:
    set AGENTIC_RAPTOR_TOPOLOGY_LLM=Qwen/Qwen2.5-3B-Instruct
    python train_proposer_diverse.py
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DEFAULT_CORPUS = ROOT / "artifacts/publication_v2/proposer_repair/corpus_diverse.json"
DEFAULT_OUT = ROOT / "artifacts/publication_v2/proposer_repair/sft_adapter_diverse"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--corpus", default=str(DEFAULT_CORPUS))
    ap.add_argument("--out", default=str(DEFAULT_OUT))
    ap.add_argument("--steps", type=int, default=1200,
                    help="765 records vs the original 85: the default is "
                         "scaled up so each record is seen a comparable "
                         "number of times")
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()

    corpus = Path(args.corpus)
    if not corpus.is_file():
        raise SystemExit(f"missing corpus: {corpus}\n"
                         "run build_diverse_corpus.py first")
    d = json.loads(corpus.read_text(encoding="utf-8"))
    print(f"corpus            : {corpus}")
    print(f"records           : {len(d['records'])}")
    print(f"distinct graphs   : {d.get('distinct_canonical_graphs')}")
    print(f"realizable families: {d.get('realizable_families')}")
    print(f"family gate       : {d.get('family_gate_status')}")
    print(f"adapter out       : {args.out}")
    print(f"steps / seed      : {args.steps} / {args.seed}\n", flush=True)

    baseline = ROOT / "artifacts/stage3e4/sft_adapter"
    if Path(args.out).resolve() == baseline.resolve():
        raise SystemExit("refusing to overwrite the baseline sft_adapter -- "
                         "the diversity comparison needs it intact")

    from agentic_raptor.llm_dpo.stage3e4 import run_sft
    rec = run_sft(steps=args.steps, seed=args.seed, corpus_path=corpus,
                  out_dir=Path(args.out))
    print("\n" + json.dumps(rec, indent=1))


if __name__ == "__main__":
    main()
